<a href="https://colab.research.google.com/github/Aditya12D/deeplearning/blob/main/VGP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from keras.models import Sequential

In [81]:
X,y = make_moons(n_samples=250, noise=0.05, random_state=42)

In [95]:
model=Sequential()
model.add(Dense(16, input_dim=2, activation='sigmoid'))
# model.add(Dense(16, activation='sigmoid'))
# model.add(Dense(16, activation='sigmoid'))
# model.add(Dense(16, activation='sigmoid'))
# reducing complezxity leads to handling vanishing gradient problem
model.add(Dense(1, activation='sigmoid'))
model

<Sequential name=sequential_8, built=True>

In [83]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [84]:
old_weights = model.get_weights()[0]

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [86]:
model.fit(X_train,y_train, epochs=100)

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5187 - loss: 0.7002  
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5086 - loss: 0.6935 
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5418 - loss: 0.6717 
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5091 - loss: 0.6793 
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5166 - loss: 0.6698 
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4934 - loss: 0.6695 
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5249 - loss: 0.6582 
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4414 - loss: 0.6757 
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4765 - loss: 0.6629 
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7089 - loss: 0.6501 
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7080 - loss: 0.6525 
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8014 - lo

In [87]:
new_weights = model.get_weights()[0]

In [88]:
model.optimizer.get_config()["learning_rate"]

0.0010000000474974513

In [89]:
gradient = (old_weights - new_weights)/ 0.001
percent_change = abs(100*(old_weights - new_weights)/ old_weights)

In [90]:
gradient

array([[-553.76086,  606.59796, -270.09085,  480.18396, -587.6795 ,
         486.95734,  571.55774,  532.67004, -340.97836,  722.8773 ,
        -496.91586, -459.3716 ,  524.2583 , -632.13995, -472.3364 ,
         377.01413],
       [ 694.7249 , -892.8118 ,  281.846  , -635.03204,  752.1732 ,
        -680.1607 , -768.4625 , -621.5703 ,  368.32993, -886.67377,
         642.8829 ,  625.94995, -722.53033,  923.4159 ,  560.303  ,
        -575.97943]], dtype=float32)

In [91]:
percent_change

array([[1402.0364  ,  136.25797 ,  134.49777 ,  209.92648 , 8795.307   ,
         101.461205,  305.8025  ,  170.03444 ,  111.86719 ,  207.10843 ,
         331.46225 ,  136.86703 ,  150.61673 ,  204.77365 ,  400.17453 ,
         127.439964],
       [ 829.96783 ,  177.76588 ,   98.23781 ,  166.89333 ,  675.80743 ,
         244.5903  ,  526.23364 , 3822.8574  ,  139.32112 ,  499.9885  ,
         307.8934  ,  150.4564  ,  370.61496 , 7888.041   ,  218.74835 ,
         120.282074]], dtype=float32)

In [92]:
old_weights

array([[-0.0394969 , -0.44518352, -0.2008144 , -0.22873911, -0.00668174,
        -0.4799444 , -0.18690422,  0.31327188, -0.30480644,  0.3490333 ,
         0.14991629,  0.33563352, -0.34807444,  0.3087018 , -0.1180326 ,
        -0.2958367 ],
       [-0.08370504, -0.5022403 ,  0.28690177,  0.38050175, -0.11129993,
        -0.27808166, -0.14603066,  0.01625931,  0.2643748 ,  0.17733884,
        -0.2088005 , -0.41603413, -0.19495445, -0.01170653,  0.25614047,
         0.47885728]], dtype=float32)

In [93]:
new_weights

array([[ 0.514264  , -1.0517815 ,  0.0692765 , -0.7089231 ,  0.58099777,
        -0.9669018 , -0.758462  , -0.21939822,  0.03617194, -0.37384403,
         0.64683217,  0.79500514, -0.87233275,  0.9408418 ,  0.3543038 ,
        -0.67285085],
       [-0.77843   ,  0.39057156,  0.00505576,  1.0155338 , -0.8634732 ,
         0.40207914,  0.6224319 ,  0.63782966, -0.10395516,  1.0640126 ,
        -0.8516834 , -1.0419841 ,  0.5275759 , -0.9351225 , -0.30416256,
         1.0548368 ]], dtype=float32)